export const patois = {
  loadingHome: 'Wull on deh',
  loadingMarketplace: 'Wi a look fi di spots',
  loadingVibe: 'Wi a find sumth nice fi yuh',
  loadingPayment: 'Wi a maths it up, wull on',
  loadingBooking: 'Wi a book it fi yuh',
  loadingRedeem: 'Wi a sort out yuh reward',
  loadingShare: 'Wi a share it',
  successPayment: 'Money dun sen',
  successBooked: 'Book off',
  successRedeemed: 'Reward dun sort',
  successSaved: 'Save up',
  successLinkCopied: 'Link dun copy',
  successDiscovery: 'Yuh find it!',
  successShoutout: 'Shoutout dun sen',
  errorGeneric: 'Sumth nah wuk',
  errorNetwork: 'Connection gone',
  errorPaymentFailed: 'Di money neva go thru',
  errorNotEnoughPoints: 'Yuh nave nuh points',
  errorClosed: 'Dem lock',
  emptySearch: 'Nuttin nuh go suh',
  emptySaved: 'Nuttin deh yah',
  emptyReceipts: 'Nah nuh receipt',
  emptyRewards: 'Nah nuh rewards',
  emptyReviews: 'Nuh nuh reviews',
  ctaPrimary: 'Fawud',
  ctaSkip: 'Skip dat',
  ctaVibe: 'Mek wi go',
  ctaSurprise: 'Shock mi',
  ctaPay: 'Pay',
  ctaConfirm: 'Dun',
  ctaBook: 'Book dis',
  ctaWelcome: 'Wah Gwan',
  ctaGroupMode: 'Pass di phone',
  ctaPushNotification: 'Pree dis'
}